### ISSUE TITLE
Error: Provided CITATION.cff does not seem valid YAML.

### ISSUE THREAD

**Issue by fnoy** [citation-file-format/cff-converter-python#145]
I installed cffconvert doing: `pip3 install --user cffconvert`

I have the following example ris file, taken from https://en.wikipedia.org/wiki/RIS_(file_format):

```
TY  - JOUR
AU  - Shannon, Claude E.
PY  - 1948/07//
TI  - A Mathematical Theory of Communication
T2  - Bell System Technical Journal
SP  - 379
EP  - 423
VL  - 27
ER  -
```

When I run `cffconvert -if foo.ris -f bibtex`, I get:

```
Traceback (most recent call last):
  File "/home/fnoy/.local/bin/cffconvert", line 10, in <module>
    sys.exit(cli())
  File "/home/fnoy/.local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/fnoy/.local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/fnoy/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fnoy/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fnoy/.local/lib/python3.7/site-packages/cffconvert/cli.py", line 60, in cli
    remove=remove, suspect_keys=suspect_keys, validate=validate)
  File "/home/fnoy/.local/lib/python3.7/site-packages/cffconvert/citation.py", line 59, in __init__
    self._parse_yaml()
  File "/home/fnoy/.local/lib/python3.7/site-packages/cffconvert/citation.py", line 86, in _parse_yaml
    raise ValueError("Provided CITATION.cff does not seem valid YAML.")
ValueError: Provided CITATION.cff does not seem valid YAML.
```

Note sure what CITATION.cff is, but I have no such file in the installation directory:

```
$ find ~/.local/lib/python3.7/site-packages/cffconvert| grep CITATION | wc -l
0
$ cffconvert --version
1.3.3
```

**Comment by fnoy** [comment]
Sorry, I looked for a ris to bibtex converter, I did not pay attention that cffconvert converts only from CFF files.

**Comment by jspaaks** [comment]
No worries! I hope you were able to solve your problem regardless.
