### ISSUE TITLE
validator stumbles when validating ggir cff

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#63]
```bash

$ cffconvert --version
0.0.5
$ cffconvert --url https://github.com/wadpac/GGIR/blob/c43d428699c6f6c863090e29e5fb9101b67f523b/CITATION.cff --validate

Traceback (most recent call last):
  File "/home/daisycutter/.venv35/bin/cffconvert", line 11, in <module>
    sys.exit(cli())
  File "/home/daisycutter/.venv35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/daisycutter/.venv35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/daisycutter/.venv35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daisycutter/.venv35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/daisycutter/.venv35/lib/python3.5/site-packages/cffconvert/cli.py", line 60, in cli
    remove=remove, suspect_keys=suspect_keys, validate=validate)
  File "/home/daisycutter/.venv35/lib/python3.5/site-packages/cffconvert/citation.py", line 54, in __init__
    self._validate()
  File "/home/daisycutter/.venv35/lib/python3.5/site-packages/cffconvert/citation.py", line 131, in _validate
    r = requests.get(schema_urls[semver])
UnboundLocalError: local variable 'semver' referenced before assignment
```

**Comment by jspaaks** [comment]
I think it may be due to https://github.com/citation-file-format/cff-converter-python/blob/f1a932b80a5261794012239b9280e046dfb7d87b/cffconvert/citation.py#L120

the regex should eat up any whitespace between the beginning of the line ``^`` and the beginning of the word ``cff-version``, i.e.

``"^\s{0,}cff-version: (['|\"])?(?P<semver>[\d\.]*)(['\"])?\s*$"``

**Comment by jspaaks** [comment]
https://github.com/citation-file-format/cff-converter-python/commit/788c4202e2efc0cedc08d350b015aa464579af52 should fix the problem but the tests need to be updated still
