### ISSUE TITLE
Failed install with python 3.7

### ISSUE THREAD

**Issue by jameshowison** [citation-file-format/cff-converter-python#80]
pip install fails with python 3.7 environment.  Happens in same way with 3.7 installed via homebrew and with a python3.7 conda environment (I couldn't get virtualenv working to test that too).  Issues seems to be with ruamel.yaml:

https://pypi.org/project/cffconvert/#files does only list python 3.6 should cffconvert refuse to install on python 3.7 environments (is that possible?)

```
conda create -n py37 -c anaconda python=3.7 
conda activate py37
pip install cffconvert
Collecting cffconvert
  Using cached https://files.pythonhosted.org/packages/79/ee/6a359b57860b48badfe5538a1ea906c500532a35f76d46b9866f915968f4/cffconvert-1.0.1.tar.gz
Collecting click==6.7 (from cffconvert)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting PyYAML==3.12 (from cffconvert)
  Using cached https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz
Collecting requests==2.18.4 (from cffconvert)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting pykwalifire==2.0.1 (from cffconvert)
  Using cached https://files.pythonhosted.org/packages/60/6d/bba1b8c3db8cdf2236819431883859f9226f89156afb72364b94d9233752/pykwalifire-2.0.1-py2.py3-none-any.whl
Collecting pytest==3.3.2 (from cffconvert)
  Using cached https://files.pythonhosted.org/packages/38/af/8dcf688d192914928393f931b7b550f2530299bbb08018b2f17efa6aab73/pytest-3.3.2-py2.py3-none-any.whl
Collecting pytest-cov==2.5.1 (from cffconvert)
  Using cached https://files.pythonhosted.org/packages/30/7d/7f6a78ae44a1248ee28cc777586c18b28a1df903470e5d34a6e25712b8aa/pytest_cov-2.5.1-py2.py3-none-any.whl
Collecting pytest-runner==4.2 (from cffconvert)
  Using cached https://files.pythonhosted.org/packages/72/a4/d7a5738a3096f22a98bec1609e237b250ebff04e5ea2930305d485337263/pytest_runner-4.2-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests==2.18.4->cffconvert)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->cffconvert)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->cffconvert)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/envs/py37/lib/python3.7/site-packages (from requests==2.18.4->cffconvert) (2018.8.24)
Collecting docopt>=0.6.2 (from pykwalifire==2.0.1->cffconvert)
Collecting ruamel.yaml<0.12.0,>=0.11.0 (from pykwalifire==2.0.1->cffconvert)
  Using cached https://files.pythonhosted.org/packages/6a/d0/1b8feda986ec3440df38ace0088b7e46d1eba769bea0f91b90c526427076/ruamel.yaml-0.11.15.tar.gz
    Complete output from command python setup.py egg_info:
    Warning: 'keywords' should be a list, got type 'NoneType'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cq/dnv1cdh95n773pwj1x49tmtr0000gp/T/pip-install-5tdy_gtf/ruamel.yaml/setup.py", line 715, in <module>
        main()
      File "/private/var/folders/cq/dnv1cdh95n773pwj1x49tmtr0000gp/T/pip-install-5tdy_gtf/ruamel.yaml/setup.py", line 712, in main
        setup(**kw)
      File "/Users/howison/miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/Users/howison/miniconda3/envs/py37/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/howison/miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/Users/howison/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/Users/howison/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/Users/howison/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cq/dnv1cdh95n773pwj1x49tmtr0000gp/T/pip-install-5tdy_gtf/ruamel.yaml/
```

**Comment by jspaaks** [comment]
Hi James, thanks for this report. 3.7 is a still rather new so I don't know how that affects things. Currently it's difficult for me to test, because I only have access to Win10 or Linux Ubuntu, no Mac though. 

Does it work for other Python versions, say, 3.5 or 3.6?

possibly relevant: https://stackoverflow.com/questions/3887381/typeerror-nonetype-object-is-not-iterable-in-python

**Comment by jameshowison** [comment]
Yes, working for 3.5 and 3.6.

**Comment by ZedThree** [comment]
I have the same issue. Updating [pykwalifire][1] to use `ramuel.yaml>=0.15` made it work for me. All the tests still pass (although weirdly not for pykwalifire)

[1]: https://github.com/sdruskat/pykwalifire

**Comment by jspaaks** [comment]
should be fixed now. closing this issue
